### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by rpgeeganage** [fatso83/mini-mocha#14]
What will you think if we change the structure of the which supports 'mini-mocha' as below?
```js
// import the library
require("fatso83/mini-mocha").install();

// test suit
describe("describe 1", function(mm) {
    mm.before(function() {});

    mm.after(function() {});

    mm.beforeEach(function() {});

    mm.afterEach(() => {});

    mm.it("main 1 it 1", function() {});

    mm.it("main 1 it 2", function() {});
});

// standalone 'it' block
it("main 1 it 2", function() {});

```

**Comment by fatso83** [comment]
The whole point of this library to me is to have somewhere to copy-paste tests that people write in the Sinon issues and run them. That means the API must be compatible with Mocha and support the most common ways of writing Mocha tests. That's it. As small a codebase as possible, but no smaller :) 

So if this means that we explicitly pass a context down, instead of using `this`, I am not in favor. Not because I don't think it's a better approach, but because we are adding features that Mocha don't have and it skews usage in the wrong direction.

**Comment by rpgeeganage** [comment]
sure. thanks.
